"""Generate a Cargo workspace skeleton for the Rust components in a module.

The CMake autocoder calls into this once per module that contains at least
one ``@ fprime-rust`` annotated component.  It produces:

* A ``Cargo.toml`` that declares one library crate per component.  Each crate
  is a ``staticlib`` so CMake can hand the resulting ``.a`` to the linker.

* A ``lib.rs`` that wires together the auto-generated ``<comp>_base.rs`` and
  the user's ``<Component>.rs``.

* A ``rust-toolchain.toml`` pinned to ``stable`` so CI behavior is
  predictable.  Users who already have a system toolchain are unaffected.
"""

from __future__ import annotations

from pathlib import Path
from typing import List

from .fpp_parser import FppComponent

CARGO_TOML_TEMPLATE = """# Auto-generated by fprime-rust.  Edit dependencies in your project's
# settings.ini if you need to extend the user crate.
[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "{lib_name}"
path = "lib.rs"
crate-type = ["staticlib"]

[dependencies]
fprime-rust = {{ path = "{runtime_path}" }}
"""

LIB_RS_TEMPLATE = """//! Auto-generated crate root for {component_name}.
//!
//! Wires together the auto-generated FFI base module and the user's
//! component behavior.  Do not edit; rerun the build instead.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

#[path = \"{base_path}\"]
pub mod {snake}_base;

#[path = \"{user_path}\"]
pub mod {snake};
"""

TOOLCHAIN_TEMPLATE = """[toolchain]
channel = \"stable\"
"""


def render_cargo_toml(component: FppComponent, runtime_path: Path) -> str:
    return CARGO_TOML_TEMPLATE.format(
        crate_name=f"fprime_rust_{component.rust_module}",
        lib_name=f"fprime_rust_{component.rust_module}",
        runtime_path=runtime_path.as_posix(),
    )


def render_lib_rs(
    component: FppComponent, user_rs_path: Path, base_rs_path: Path
) -> str:
    return LIB_RS_TEMPLATE.format(
        component_name=component.name,
        snake=component.rust_module,
        user_path=user_rs_path.as_posix(),
        base_path=base_rs_path.as_posix(),
    )


def render_toolchain() -> str:
    return TOOLCHAIN_TEMPLATE
