"""Generate the C++ "shim" component implementation that bridges to Rust.

The shim is a concrete subclass of the FPP-autocoded ``<Component>ComponentBase``.
It overrides every command handler with a small body that calls into a
matching ``extern "C"`` Rust function.  Telemetry/event/parameter access is
exposed in the opposite direction via a small set of free C functions which
the Rust runtime declares in turn (see ``rust_generator.py``).

Generated artifacts (per annotated component ``Foo`` in module ``Bar``):

* ``FooRustImpl.hpp`` -- declares ``Bar::Foo`` extending ``Bar::FooComponentBase``.
* ``FooRustImpl.cpp`` -- defines the constructor, the command-handler bodies,
  and the C-callable ``rust_<comp>_*`` "sink" functions used by Rust to talk
  back to F Prime.

The naming convention mirrors the FPP/Python autocoder: instead of the user
hand-writing ``Foo.cpp``, ``FooRustImpl.cpp`` is fully autocoded and the user
implements behavior in ``Foo.rs``.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List

from .fpp_parser import FppArg, FppComponent, severity_to_log_infix

INDENT = "    "


def _ffi_name(component: FppComponent, suffix: str) -> str:
    """Produce a stable C symbol for the FFI hop.

    Uses the lowercase component name (``foo``) plus the suffix.  This matches
    the Rust ``#[no_mangle]`` exported function names.
    """
    return f"rust_{component.rust_module}_{suffix}"


def _arg_decl_list(args: List[FppArg]) -> str:
    return ", ".join(f"{a.cpp_type} {a.name}" for a in args)


def _arg_name_list(args: List[FppArg]) -> str:
    return ", ".join(a.name for a in args)


def _open_namespace(component: FppComponent) -> str:
    if not component.namespace:
        return ""
    return "\n".join(f"namespace {ns} {{" for ns in component.namespace) + "\n"


def _close_namespace(component: FppComponent) -> str:
    if not component.namespace:
        return ""
    return (
        "\n".join(f"}}  // namespace {ns}" for ns in reversed(component.namespace))
        + "\n"
    )


def render_header(component: FppComponent) -> str:
    """Render ``<Component>RustImpl.hpp``."""
    name = component.name
    base = f"{name}ComponentBase"
    guard = f"FPRIME_RUST_{component.rust_module.upper()}_HPP"
    cmd_decls = []
    for cmd in component.commands:
        args = [FppArg("opCode", "FwOpcodeType"), FppArg("cmdSeq", "U32")] + cmd.args
        cmd_decls.append(
            f"{INDENT}void {cmd.name}_cmdHandler({_arg_decl_list(args)}) override;"
        )

    return f"""// Auto-generated by fprime-rust. Do not edit by hand.
//
// Header for the Rust-backed implementation of {component.cpp_fqn}.
// The class derives from the FPP-autocoded {base} and forwards all
// command handlers to a Rust implementation via an extern "C" FFI.

#ifndef {guard}
#define {guard}

#include "{base}.hpp"

{_open_namespace(component)}

class {name} final : public {base} {{
  public:
    explicit {name}(const char* compName);
    {name}(const {name}&) = delete;
    {name}& operator=(const {name}&) = delete;
    ~{name}() override;

    //! Standard F Prime init wrapper.  Forwards through to the FPP-generated
    //! base class after the Rust state has been allocated by the constructor.
    void init(NATIVE_INT_TYPE queueDepth, NATIVE_INT_TYPE instance);

    //! Opaque handle to the Rust ``Box<dyn Impl>`` for this component.  Marked
    //! ``public`` so the auto-coded sink functions in this translation unit
    //! can read it; treat it as private to user code.
    void* m_rust_impl {{nullptr}};

  private:
{chr(10).join(cmd_decls) if cmd_decls else INDENT + "// (no commands)"}
}};

{_close_namespace(component)}

#endif  // {guard}
"""


def render_source(component: FppComponent) -> str:
    """Render ``<Component>RustImpl.cpp``."""
    name = component.name
    fqn = component.cpp_fqn
    open_ns = _open_namespace(component)
    close_ns = _close_namespace(component)

    # ---- extern "C" declarations of the Rust handlers ----
    # The dispatch layer takes TWO opaque pointers: ``rust_self`` (the
    # ``Box<dyn Component>`` allocated by ``rust_<comp>_new``) is used to
    # locate the user state, while ``cpp_self`` is the C++ component
    # ``this`` that Rust hands back unchanged when calling the sink
    # functions below.  Splitting them avoids the lifetime confusion of
    # multiplexing two distinct types through a single ``void*``.
    rust_decls: List[str] = []
    for cmd in component.commands:
        args = [
            FppArg("rust_self", "void*"),
            FppArg("cpp_self", "void*"),
            FppArg("opCode", "FwOpcodeType"),
            FppArg("cmdSeq", "U32"),
        ] + cmd.args
        sym = _ffi_name(component, f"cmd_{cmd.name}")
        rust_decls.append(f"void {sym}({_arg_decl_list(args)});")
    rust_decls.append(f"void* {_ffi_name(component, 'new')}();")
    rust_decls.append(f"void {_ffi_name(component, 'free')}(void* rust_self);")

    # ---- C++ -> Rust "sink" implementations exported back to Rust ----
    sink_funcs: List[str] = []
    # tlmWrite_*
    for ch in component.telemetry:
        sym = _ffi_name(component, f"tlm_{ch.name}")
        sink_funcs.append(
            f"""extern \"C\" void {sym}(void* fp_self, {ch.cpp_type} value) {{
{INDENT}auto* self = static_cast<{fqn}*>(fp_self);
{INDENT}self->tlmWrite_{ch.name}(value);
}}"""
        )
    # log_*
    for ev in component.events:
        sym = _ffi_name(component, f"event_{ev.name}")
        args = [FppArg("fp_self", "void*")] + ev.args
        body_args = _arg_name_list(ev.args)
        infix = severity_to_log_infix(ev.severity)
        sink_funcs.append(f"""extern \"C\" void {sym}({_arg_decl_list(args)}) {{
{INDENT}auto* self = static_cast<{fqn}*>(fp_self);
{INDENT}self->log_{infix}_{ev.name}({body_args});
}}""")
    # paramGet_*
    for prm in component.parameters:
        sym = _ffi_name(component, f"param_{prm.name}")
        sink_funcs.append(
            f"""extern \"C\" {prm.cpp_type} {sym}(void* fp_self, U8* outValid) {{
{INDENT}auto* self = static_cast<{fqn}*>(fp_self);
{INDENT}Fw::ParamValid valid;
{INDENT}{prm.cpp_type} v = self->paramGet_{prm.name}(valid);
{INDENT}if (outValid) {{
{INDENT*2}*outValid = static_cast<U8>(valid.e);
{INDENT}}}
{INDENT}return v;
}}"""
        )
    # cmdResponse
    cmd_resp = _ffi_name(component, "cmdResponse")
    sink_funcs.append(
        f"""extern \"C\" void {cmd_resp}(void* fp_self, FwOpcodeType opCode, U32 cmdSeq, U8 status) {{
{INDENT}auto* self = static_cast<{fqn}*>(fp_self);
{INDENT}Fw::CmdResponse resp;
{INDENT}resp.e = static_cast<Fw::CmdResponse::T>(status);
{INDENT}self->cmdResponse_out(opCode, cmdSeq, resp);
}}"""
    )

    # ---- C++ command handler forwarders ----
    cmd_impls: List[str] = []
    for cmd in component.commands:
        sym = _ffi_name(component, f"cmd_{cmd.name}")
        args = [FppArg("opCode", "FwOpcodeType"), FppArg("cmdSeq", "U32")] + cmd.args
        # Always forward two opaque pointers: the Rust state (``m_rust_impl``)
        # *and* the C++ ``this``.  Rust returns ``cpp_self`` unchanged when it
        # calls the sink functions below, which static_cast it back to the
        # concrete component type.
        forwarded = [
            "this->m_rust_impl",
            "static_cast<void*>(this)",
        ] + [a.name for a in args]
        cmd_impls.append(
            f"""void {name}::{cmd.name}_cmdHandler({_arg_decl_list(args)}) {{
{INDENT}::{sym}({", ".join(forwarded)});
}}"""
        )

    return f"""// Auto-generated by fprime-rust. Do not edit by hand.
//
// Implementation of the C++ shim for {fqn}.  Every override forwards to a
// Rust function via an extern \"C\" FFI; in the opposite direction this file
// also defines the small set of free \"sink\" functions Rust uses to publish
// telemetry, log events, and respond to commands.

#include "{name}RustImpl.hpp"
#include "Fw/Cmd/CmdResponse.hpp"

extern "C" {{
{chr(10).join(rust_decls)}
}}  // extern "C"

{open_ns}

namespace {{
//! Hidden state attached to the running C++ instance via init().  The pointer
//! is opaque to C++ but is interpreted as ``Box<Component>`` by Rust.
struct RustImplHandle {{
    void* opaque;
}};
}}  // namespace

{name}::{name}(const char* compName)
{INDENT}: {name}ComponentBase(compName) {{
{INDENT}// Allocate the Rust-side state immediately so that handlers always
{INDENT}// have a valid ``self``.  The pointer is freed in the destructor.
{INDENT}this->m_rust_impl = ::{_ffi_name(component, 'new')}();
}}

{name}::~{name}() {{
{INDENT}if (this->m_rust_impl) {{
{INDENT*2}::{_ffi_name(component, 'free')}(this->m_rust_impl);
{INDENT*2}this->m_rust_impl = nullptr;
{INDENT}}}
}}

void {name}::init(NATIVE_INT_TYPE queueDepth, NATIVE_INT_TYPE instance) {{
{INDENT}{name}ComponentBase::init(queueDepth, instance);
}}

{chr(10).join(cmd_impls)}

{close_ns}

// -------------------------------------------------------------------------
// C++ -> Rust "sinks": these are called from Rust to talk back to F Prime.
// They live in the global namespace with stable C linkage.
// -------------------------------------------------------------------------
{chr(10).join(sink_funcs)}
"""


@dataclass
class CppArtifacts:
    header_path: Path
    source_path: Path
    header: str
    source: str


def generate_cpp(component: FppComponent, output_dir: Path) -> CppArtifacts:
    header = render_header(component)
    source = render_source(component)
    header_path = output_dir / f"{component.name}RustImpl.hpp"
    source_path = output_dir / f"{component.name}RustImpl.cpp"
    return CppArtifacts(
        header_path=header_path,
        source_path=source_path,
        header=header,
        source=source,
    )
