// ======================================================================
// \title  CfdpPduTest.cpp
// \author devin
// \brief  Unit tests for CFDP PDU serialization/deserialization.
//
// Tests verify interoperability with the Python spacepackets library
// by checking against reference byte sequences generated by spacepackets.
// ======================================================================

#include <gtest/gtest.h>
#include <Svc/Cfdp/Types/CfdpPdu.hpp>
#include <cstring>

namespace Svc {
namespace Cfdp {

// -----------------------------------------------------------------------
// Reference PDU byte sequences generated by spacepackets v0.31.0
// Config: 2-byte entity IDs (src=1, dst=2), 2-byte seq num (1),
//         unacknowledged mode, no CRC, small file, toward receiver
// -----------------------------------------------------------------------

// Metadata PDU: fileSize=100, src="source.bin", dst="dest.bin"
static const U8 REF_METADATA_PDU[] = {
    0x24, 0x00, 0x1a, 0x11, 0x00, 0x01, 0x00, 0x01,
    0x00, 0x02, 0x07, 0x00, 0x00, 0x00, 0x00, 0x64,
    0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
    0x62, 0x69, 0x6e, 0x08, 0x64, 0x65, 0x73, 0x74,
    0x2e, 0x62, 0x69, 0x6e
};

// File Data PDU: offset=0, data={0x01,0x02,0x03,0x04,0x05}
static const U8 REF_FILE_DATA_PDU[] = {
    0x34, 0x00, 0x09, 0x11, 0x00, 0x01, 0x00, 0x01,
    0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02,
    0x03, 0x04, 0x05
};

// File Data PDU: offset=10, data={0xAA,0xBB,0xCC}
static const U8 REF_FILE_DATA_PDU_OFFSET10[] = {
    0x34, 0x00, 0x07, 0x11, 0x00, 0x01, 0x00, 0x01,
    0x00, 0x02, 0x00, 0x00, 0x00, 0x0a, 0xaa, 0xbb,
    0xcc
};

// EOF PDU: conditionCode=NO_ERROR, checksum=0x12345678, fileSize=100
static const U8 REF_EOF_PDU[] = {
    0x24, 0x00, 0x0a, 0x11, 0x00, 0x01, 0x00, 0x01,
    0x00, 0x02, 0x04, 0x00, 0x12, 0x34, 0x56, 0x78,
    0x00, 0x00, 0x00, 0x64
};

// EOF PDU (Cancel): conditionCode=CANCEL_REQUEST_RECEIVED, checksum=0, fileSize=50
static const U8 REF_EOF_CANCEL_PDU[] = {
    0x24, 0x00, 0x0a, 0x11, 0x00, 0x01, 0x00, 0x01,
    0x00, 0x02, 0x04, 0xf0, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x32
};

// Finished PDU: conditionCode=NO_ERROR, deliveryCode=DATA_COMPLETE, fileStatus=DISCARDED_DELIBERATELY
// Direction is TOWARDS_SENDER
static const U8 REF_FINISHED_PDU[] = {
    0x2c, 0x00, 0x02, 0x11, 0x00, 0x01, 0x00, 0x01,
    0x00, 0x02, 0x05, 0x00
};

static const U32 HEADER_SIZE = 10;  // 4 fixed + 2*2 entity IDs + 2 seq num

// -----------------------------------------------------------------------
// PduHeader Tests
// -----------------------------------------------------------------------

class PduHeaderTest : public ::testing::Test {
  protected:
    void SetUp() override {
        header.version = CFDP_VERSION;
        header.pduType = PduType::FILE_DIRECTIVE;
        header.direction = Direction::TOWARD_RECEIVER;
        header.mode = TransmissionMode::UNACKNOWLEDGED;
        header.crcFlag = false;
        header.largeFileFlag = false;
        header.dataFieldLength = 0;
        header.segmentationControl = false;
        header.entityIdLength = 1;  // 2-byte entity IDs
        header.segmentMetadataFlag = false;
        header.seqNumLength = 1;  // 2-byte seq nums
        header.sourceEntityId = 1;
        header.transactionSeqNum = 1;
        header.destinationEntityId = 2;
    }

    PduHeader header;
};

TEST_F(PduHeaderTest, SerializeSize) {
    EXPECT_EQ(HEADER_SIZE, header.getSerializedSize());
}

TEST_F(PduHeaderTest, SerializeDeserializeRoundTrip) {
    U8 buf[64];
    U32 serializedSize = header.serialize(buf, sizeof(buf));
    EXPECT_EQ(HEADER_SIZE, serializedSize);

    PduHeader parsed;
    U32 parsedSize = parsed.deserialize(buf, serializedSize);
    EXPECT_EQ(HEADER_SIZE, parsedSize);

    EXPECT_EQ(header.version, parsed.version);
    EXPECT_EQ(header.pduType, parsed.pduType);
    EXPECT_EQ(header.direction, parsed.direction);
    EXPECT_EQ(header.mode, parsed.mode);
    EXPECT_EQ(header.crcFlag, parsed.crcFlag);
    EXPECT_EQ(header.largeFileFlag, parsed.largeFileFlag);
    EXPECT_EQ(header.dataFieldLength, parsed.dataFieldLength);
    EXPECT_EQ(header.segmentationControl, parsed.segmentationControl);
    EXPECT_EQ(header.entityIdLength, parsed.entityIdLength);
    EXPECT_EQ(header.segmentMetadataFlag, parsed.segmentMetadataFlag);
    EXPECT_EQ(header.seqNumLength, parsed.seqNumLength);
    EXPECT_EQ(header.sourceEntityId, parsed.sourceEntityId);
    EXPECT_EQ(header.transactionSeqNum, parsed.transactionSeqNum);
    EXPECT_EQ(header.destinationEntityId, parsed.destinationEntityId);
}

TEST_F(PduHeaderTest, DeserializeFromSpacepacketsMetadata) {
    PduHeader parsed;
    U32 parsedSize = parsed.deserialize(REF_METADATA_PDU, sizeof(REF_METADATA_PDU));
    EXPECT_EQ(HEADER_SIZE, parsedSize);

    EXPECT_EQ(static_cast<U8>(CFDP_VERSION), parsed.version);
    EXPECT_EQ(PduType::FILE_DIRECTIVE, parsed.pduType);
    EXPECT_EQ(Direction::TOWARD_RECEIVER, parsed.direction);
    EXPECT_EQ(TransmissionMode::UNACKNOWLEDGED, parsed.mode);
    EXPECT_FALSE(parsed.crcFlag);
    EXPECT_FALSE(parsed.largeFileFlag);
    // Data field length from bytes 1-2: 0x001a = 26
    EXPECT_EQ(static_cast<U16>(26), parsed.dataFieldLength);
    EXPECT_EQ(static_cast<U8>(1), parsed.entityIdLength);  // 2-byte entity IDs
    EXPECT_EQ(static_cast<U8>(1), parsed.seqNumLength);  // 2-byte seq nums
    EXPECT_EQ(static_cast<U64>(1), parsed.sourceEntityId);
    EXPECT_EQ(static_cast<U64>(1), parsed.transactionSeqNum);
    EXPECT_EQ(static_cast<U64>(2), parsed.destinationEntityId);
}

TEST_F(PduHeaderTest, DeserializeFromSpacepacketsFileData) {
    PduHeader parsed;
    U32 parsedSize = parsed.deserialize(REF_FILE_DATA_PDU, sizeof(REF_FILE_DATA_PDU));
    EXPECT_EQ(HEADER_SIZE, parsedSize);

    EXPECT_EQ(PduType::FILE_DATA, parsed.pduType);
    EXPECT_EQ(Direction::TOWARD_RECEIVER, parsed.direction);
    EXPECT_EQ(TransmissionMode::UNACKNOWLEDGED, parsed.mode);
    // Data field length: 0x0009 = 9 (4 bytes offset + 5 bytes data)
    EXPECT_EQ(static_cast<U16>(9), parsed.dataFieldLength);
}

TEST_F(PduHeaderTest, SerializeMatchesSpacepackets) {
    // Set data field length to match metadata PDU
    header.dataFieldLength = 26;
    U8 buf[64];
    U32 serializedSize = header.serialize(buf, sizeof(buf));
    EXPECT_EQ(HEADER_SIZE, serializedSize);

    // Compare header bytes with spacepackets reference
    for (U32 i = 0; i < HEADER_SIZE; i++) {
        EXPECT_EQ(REF_METADATA_PDU[i], buf[i])
            << "Mismatch at byte " << i;
    }
}

TEST_F(PduHeaderTest, DeserializeTooSmallBuffer) {
    PduHeader parsed;
    // Less than minimum 4 bytes
    U32 parsedSize = parsed.deserialize(REF_METADATA_PDU, 3);
    EXPECT_EQ(static_cast<U32>(0), parsedSize);

    // Enough for fixed header but not variable part
    parsedSize = parsed.deserialize(REF_METADATA_PDU, 5);
    EXPECT_EQ(static_cast<U32>(0), parsedSize);
}

TEST_F(PduHeaderTest, SerializeTooSmallBuffer) {
    U8 buf[4];
    U32 serializedSize = header.serialize(buf, sizeof(buf));
    EXPECT_EQ(static_cast<U32>(0), serializedSize);
}

// -----------------------------------------------------------------------
// MetadataPdu Tests
// -----------------------------------------------------------------------

class MetadataPduTest : public ::testing::Test {
  protected:
    void SetUp() override {
        metadata.closureRequested = false;
        metadata.checksumType = 0;  // Modular
        metadata.fileSize = 100;
        const char* src = "source.bin";
        const char* dst = "dest.bin";
        metadata.sourceFileNameLen = static_cast<U8>(std::strlen(src));
        (void)std::memcpy(metadata.sourceFileName, src, metadata.sourceFileNameLen);
        metadata.sourceFileName[metadata.sourceFileNameLen] = '\0';
        metadata.destFileNameLen = static_cast<U8>(std::strlen(dst));
        (void)std::memcpy(metadata.destFileName, dst, metadata.destFileNameLen);
        metadata.destFileName[metadata.destFileNameLen] = '\0';
    }

    MetadataPdu metadata;
};

TEST_F(MetadataPduTest, SerializeDeserializeRoundTrip) {
    U8 buf[256];
    U32 serializedSize = metadata.serialize(buf, sizeof(buf));
    EXPECT_GT(serializedSize, static_cast<U32>(0));

    MetadataPdu parsed;
    U32 parsedSize = parsed.deserialize(buf, serializedSize, false);
    EXPECT_EQ(serializedSize, parsedSize);

    EXPECT_EQ(metadata.closureRequested, parsed.closureRequested);
    EXPECT_EQ(metadata.checksumType, parsed.checksumType);
    EXPECT_EQ(metadata.fileSize, parsed.fileSize);
    EXPECT_EQ(metadata.sourceFileNameLen, parsed.sourceFileNameLen);
    EXPECT_STREQ(metadata.sourceFileName, parsed.sourceFileName);
    EXPECT_EQ(metadata.destFileNameLen, parsed.destFileNameLen);
    EXPECT_STREQ(metadata.destFileName, parsed.destFileName);
}

TEST_F(MetadataPduTest, DeserializeFromSpacepackets) {
    // The metadata data field starts after the header (10 bytes) and directive code (1 byte)
    const U8* metadataParams = REF_METADATA_PDU + HEADER_SIZE + 1;
    const U32 metadataParamsLen = sizeof(REF_METADATA_PDU) - HEADER_SIZE - 1;

    MetadataPdu parsed;
    U32 parsedSize = parsed.deserialize(metadataParams, metadataParamsLen, false);
    EXPECT_GT(parsedSize, static_cast<U32>(0));

    EXPECT_FALSE(parsed.closureRequested);
    EXPECT_EQ(static_cast<U8>(0), parsed.checksumType);  // Modular
    EXPECT_EQ(static_cast<U32>(100), parsed.fileSize);
    EXPECT_STREQ("source.bin", parsed.sourceFileName);
    EXPECT_STREQ("dest.bin", parsed.destFileName);
}

TEST_F(MetadataPduTest, SerializeMatchesSpacepackets) {
    U8 buf[256];
    U32 serializedSize = metadata.serialize(buf, sizeof(buf));
    EXPECT_GT(serializedSize, static_cast<U32>(0));

    // Compare with the data field portion of the reference PDU
    // (after header + directive code byte)
    const U8* refParams = REF_METADATA_PDU + HEADER_SIZE + 1;
    const U32 refParamsLen = sizeof(REF_METADATA_PDU) - HEADER_SIZE - 1;

    EXPECT_EQ(refParamsLen, serializedSize);
    for (U32 i = 0; i < serializedSize; i++) {
        EXPECT_EQ(refParams[i], buf[i])
            << "Mismatch at metadata param byte " << i;
    }
}

TEST_F(MetadataPduTest, SerializeFullPduMatchesSpacepackets) {
    // Build a complete metadata PDU and compare with reference
    PduHeader header;
    header.version = CFDP_VERSION;
    header.pduType = PduType::FILE_DIRECTIVE;
    header.direction = Direction::TOWARD_RECEIVER;
    header.mode = TransmissionMode::UNACKNOWLEDGED;
    header.crcFlag = false;
    header.largeFileFlag = false;
    header.segmentationControl = false;
    header.entityIdLength = 1;
    header.segmentMetadataFlag = false;
    header.seqNumLength = 1;
    header.sourceEntityId = 1;
    header.transactionSeqNum = 1;
    header.destinationEntityId = 2;

    U8 paramBuf[256];
    U32 paramLen = metadata.serialize(paramBuf, sizeof(paramBuf));
    ASSERT_GT(paramLen, static_cast<U32>(0));

    header.dataFieldLength = static_cast<U16>(1 + paramLen);

    U8 fullPdu[512];
    U32 totalLen = serializeDirectivePdu(
        header, DirectiveCode::METADATA_PDU,
        paramBuf, paramLen, fullPdu, sizeof(fullPdu)
    );
    ASSERT_GT(totalLen, static_cast<U32>(0));

    EXPECT_EQ(sizeof(REF_METADATA_PDU), totalLen);
    for (U32 i = 0; i < totalLen; i++) {
        EXPECT_EQ(REF_METADATA_PDU[i], fullPdu[i])
            << "Mismatch at byte " << i;
    }
}

TEST_F(MetadataPduTest, DeserializeTooSmallBuffer) {
    MetadataPdu parsed;
    U32 parsedSize = parsed.deserialize(REF_METADATA_PDU, 3, false);
    EXPECT_EQ(static_cast<U32>(0), parsedSize);
}

// -----------------------------------------------------------------------
// FileDataPdu Tests
// -----------------------------------------------------------------------

class FileDataPduTest : public ::testing::Test {};

TEST_F(FileDataPduTest, SerializeDeserializeRoundTrip) {
    U8 data[] = {0x01, 0x02, 0x03, 0x04, 0x05};
    FileDataPdu original;
    original.offset = 0;
    original.data = data;
    original.dataSize = sizeof(data);

    U8 buf[64];
    U32 serializedSize = original.serialize(buf, sizeof(buf));
    EXPECT_EQ(static_cast<U32>(4 + sizeof(data)), serializedSize);

    FileDataPdu parsed;
    U32 parsedSize = parsed.deserialize(buf, serializedSize, false);
    EXPECT_EQ(serializedSize, parsedSize);

    EXPECT_EQ(original.offset, parsed.offset);
    EXPECT_EQ(original.dataSize, parsed.dataSize);
    EXPECT_EQ(0, std::memcmp(data, parsed.data, parsed.dataSize));
}

TEST_F(FileDataPduTest, DeserializeFromSpacepackets) {
    const U8* dataField = REF_FILE_DATA_PDU + HEADER_SIZE;
    const U32 dataFieldLen = sizeof(REF_FILE_DATA_PDU) - HEADER_SIZE;

    FileDataPdu parsed;
    U32 parsedSize = parsed.deserialize(dataField, dataFieldLen, false);
    EXPECT_GT(parsedSize, static_cast<U32>(0));

    EXPECT_EQ(static_cast<U32>(0), parsed.offset);
    EXPECT_EQ(static_cast<U32>(5), parsed.dataSize);
    EXPECT_EQ(0x01, parsed.data[0]);
    EXPECT_EQ(0x05, parsed.data[4]);
}

TEST_F(FileDataPduTest, DeserializeFromSpacepacketsWithOffset) {
    const U8* dataField = REF_FILE_DATA_PDU_OFFSET10 + HEADER_SIZE;
    const U32 dataFieldLen = sizeof(REF_FILE_DATA_PDU_OFFSET10) - HEADER_SIZE;

    FileDataPdu parsed;
    U32 parsedSize = parsed.deserialize(dataField, dataFieldLen, false);
    EXPECT_GT(parsedSize, static_cast<U32>(0));

    EXPECT_EQ(static_cast<U32>(10), parsed.offset);
    EXPECT_EQ(static_cast<U32>(3), parsed.dataSize);
    EXPECT_EQ(0xAA, parsed.data[0]);
    EXPECT_EQ(0xBB, parsed.data[1]);
    EXPECT_EQ(0xCC, parsed.data[2]);
}

TEST_F(FileDataPduTest, SerializeMatchesSpacepackets) {
    U8 data[] = {0x01, 0x02, 0x03, 0x04, 0x05};
    FileDataPdu fileData;
    fileData.offset = 0;
    fileData.data = data;
    fileData.dataSize = sizeof(data);

    PduHeader header;
    header.version = CFDP_VERSION;
    header.pduType = PduType::FILE_DATA;
    header.direction = Direction::TOWARD_RECEIVER;
    header.mode = TransmissionMode::UNACKNOWLEDGED;
    header.crcFlag = false;
    header.largeFileFlag = false;
    header.dataFieldLength = static_cast<U16>(4 + sizeof(data));
    header.segmentationControl = false;
    header.entityIdLength = 1;
    header.segmentMetadataFlag = false;
    header.seqNumLength = 1;
    header.sourceEntityId = 1;
    header.transactionSeqNum = 1;
    header.destinationEntityId = 2;

    U8 fullPdu[64];
    U32 totalLen = serializeFileDataPdu(header, fileData, fullPdu, sizeof(fullPdu));
    ASSERT_GT(totalLen, static_cast<U32>(0));

    EXPECT_EQ(sizeof(REF_FILE_DATA_PDU), totalLen);
    for (U32 i = 0; i < totalLen; i++) {
        EXPECT_EQ(REF_FILE_DATA_PDU[i], fullPdu[i])
            << "Mismatch at byte " << i;
    }
}

TEST_F(FileDataPduTest, DeserializeTooSmallBuffer) {
    FileDataPdu parsed;
    U8 buf[] = {0x00, 0x00};
    U32 parsedSize = parsed.deserialize(buf, sizeof(buf), false);
    EXPECT_EQ(static_cast<U32>(0), parsedSize);
}

// -----------------------------------------------------------------------
// EofPdu Tests
// -----------------------------------------------------------------------

class EofPduTest : public ::testing::Test {};

TEST_F(EofPduTest, SerializeDeserializeRoundTrip) {
    EofPdu original;
    original.conditionCode = ConditionCode::NO_ERROR;
    original.fileChecksum = 0x12345678;
    original.fileSize = 100;

    U8 buf[16];
    U32 serializedSize = original.serialize(buf, sizeof(buf));
    EXPECT_EQ(static_cast<U32>(9), serializedSize);

    EofPdu parsed;
    U32 parsedSize = parsed.deserialize(buf, serializedSize, false);
    EXPECT_EQ(serializedSize, parsedSize);

    EXPECT_EQ(original.conditionCode, parsed.conditionCode);
    EXPECT_EQ(original.fileChecksum, parsed.fileChecksum);
    EXPECT_EQ(original.fileSize, parsed.fileSize);
}

TEST_F(EofPduTest, DeserializeFromSpacepackets) {
    // EOF data field starts after header + directive code
    const U8* eofParams = REF_EOF_PDU + HEADER_SIZE + 1;
    const U32 eofParamsLen = sizeof(REF_EOF_PDU) - HEADER_SIZE - 1;

    EofPdu parsed;
    U32 parsedSize = parsed.deserialize(eofParams, eofParamsLen, false);
    EXPECT_GT(parsedSize, static_cast<U32>(0));

    EXPECT_EQ(ConditionCode::NO_ERROR, parsed.conditionCode);
    EXPECT_EQ(static_cast<U32>(0x12345678), parsed.fileChecksum);
    EXPECT_EQ(static_cast<U32>(100), parsed.fileSize);
}

TEST_F(EofPduTest, DeserializeCancelFromSpacepackets) {
    const U8* eofParams = REF_EOF_CANCEL_PDU + HEADER_SIZE + 1;
    const U32 eofParamsLen = sizeof(REF_EOF_CANCEL_PDU) - HEADER_SIZE - 1;

    EofPdu parsed;
    U32 parsedSize = parsed.deserialize(eofParams, eofParamsLen, false);
    EXPECT_GT(parsedSize, static_cast<U32>(0));

    EXPECT_EQ(ConditionCode::CANCEL_REQUEST_RECEIVED, parsed.conditionCode);
    EXPECT_EQ(static_cast<U32>(0), parsed.fileChecksum);
    EXPECT_EQ(static_cast<U32>(50), parsed.fileSize);
}

TEST_F(EofPduTest, SerializeMatchesSpacepackets) {
    EofPdu eofPdu;
    eofPdu.conditionCode = ConditionCode::NO_ERROR;
    eofPdu.fileChecksum = 0x12345678;
    eofPdu.fileSize = 100;

    U8 paramBuf[16];
    U32 paramLen = eofPdu.serialize(paramBuf, sizeof(paramBuf));
    ASSERT_EQ(static_cast<U32>(9), paramLen);

    // Compare with the reference EOF params (after header + directive code)
    const U8* refParams = REF_EOF_PDU + HEADER_SIZE + 1;
    for (U32 i = 0; i < paramLen; i++) {
        EXPECT_EQ(refParams[i], paramBuf[i])
            << "Mismatch at EOF param byte " << i;
    }
}

TEST_F(EofPduTest, SerializeFullPduMatchesSpacepackets) {
    PduHeader header;
    header.version = CFDP_VERSION;
    header.pduType = PduType::FILE_DIRECTIVE;
    header.direction = Direction::TOWARD_RECEIVER;
    header.mode = TransmissionMode::UNACKNOWLEDGED;
    header.crcFlag = false;
    header.largeFileFlag = false;
    header.segmentationControl = false;
    header.entityIdLength = 1;
    header.segmentMetadataFlag = false;
    header.seqNumLength = 1;
    header.sourceEntityId = 1;
    header.transactionSeqNum = 1;
    header.destinationEntityId = 2;

    EofPdu eofPdu;
    eofPdu.conditionCode = ConditionCode::NO_ERROR;
    eofPdu.fileChecksum = 0x12345678;
    eofPdu.fileSize = 100;

    U8 paramBuf[16];
    U32 paramLen = eofPdu.serialize(paramBuf, sizeof(paramBuf));
    ASSERT_GT(paramLen, static_cast<U32>(0));

    header.dataFieldLength = static_cast<U16>(1 + paramLen);

    U8 fullPdu[64];
    U32 totalLen = serializeDirectivePdu(
        header, DirectiveCode::EOF_PDU,
        paramBuf, paramLen, fullPdu, sizeof(fullPdu)
    );
    ASSERT_GT(totalLen, static_cast<U32>(0));

    EXPECT_EQ(sizeof(REF_EOF_PDU), totalLen);
    for (U32 i = 0; i < totalLen; i++) {
        EXPECT_EQ(REF_EOF_PDU[i], fullPdu[i])
            << "Mismatch at byte " << i;
    }
}

TEST_F(EofPduTest, DeserializeTooSmallBuffer) {
    EofPdu parsed;
    U8 buf[] = {0x00, 0x00, 0x00, 0x00};
    U32 parsedSize = parsed.deserialize(buf, sizeof(buf), false);
    EXPECT_EQ(static_cast<U32>(0), parsedSize);
}

// -----------------------------------------------------------------------
// FinishedPdu Tests
// -----------------------------------------------------------------------

class FinishedPduTest : public ::testing::Test {};

TEST_F(FinishedPduTest, SerializeDeserializeRoundTrip) {
    FinishedPdu original;
    original.conditionCode = ConditionCode::NO_ERROR;
    original.deliveryCode = DeliveryCode::DATA_COMPLETE;
    original.fileStatus = FileStatus::DISCARDED_DELIBERATELY;

    U8 buf[4];
    U32 serializedSize = original.serialize(buf, sizeof(buf));
    EXPECT_EQ(static_cast<U32>(1), serializedSize);

    FinishedPdu parsed;
    U32 parsedSize = parsed.deserialize(buf, serializedSize);
    EXPECT_EQ(static_cast<U32>(1), parsedSize);

    EXPECT_EQ(original.conditionCode, parsed.conditionCode);
    EXPECT_EQ(original.deliveryCode, parsed.deliveryCode);
    EXPECT_EQ(original.fileStatus, parsed.fileStatus);
}

TEST_F(FinishedPduTest, DeserializeFromSpacepackets) {
    // Finished data field: after header + directive code
    const U8* finishedParams = REF_FINISHED_PDU + HEADER_SIZE + 1;
    const U32 finishedParamsLen = sizeof(REF_FINISHED_PDU) - HEADER_SIZE - 1;

    FinishedPdu parsed;
    U32 parsedSize = parsed.deserialize(finishedParams, finishedParamsLen);
    EXPECT_EQ(static_cast<U32>(1), parsedSize);

    EXPECT_EQ(ConditionCode::NO_ERROR, parsed.conditionCode);
    EXPECT_EQ(DeliveryCode::DATA_COMPLETE, parsed.deliveryCode);
    EXPECT_EQ(FileStatus::DISCARDED_DELIBERATELY, parsed.fileStatus);
}

TEST_F(FinishedPduTest, BitFieldLayout) {
    // Per CCSDS 727.0-B-5 Table 5-7:
    // conditionCode(4) | spare(1) | deliveryCode(1) | fileStatus(2)
    //
    // Test with non-zero values to verify bit positions
    FinishedPdu original;
    original.conditionCode = ConditionCode::CANCEL_REQUEST_RECEIVED;  // 0x0F
    original.deliveryCode = DeliveryCode::DATA_INCOMPLETE;  // 1
    original.fileStatus = FileStatus::DISCARDED_FILESTORE_REJECTION;  // 2

    U8 buf[4];
    U32 serializedSize = original.serialize(buf, sizeof(buf));
    EXPECT_EQ(static_cast<U32>(1), serializedSize);

    // Expected byte: 0xF0 | 0x04 | 0x01 = 0xF5
    // conditionCode(0x0F) << 4 = 0xF0
    // deliveryCode(1) << 2 = 0x04
    // fileStatus(1) = 0x01
    EXPECT_EQ(0xF5, buf[0]);

    FinishedPdu parsed;
    parsed.deserialize(buf, 1);
    EXPECT_EQ(ConditionCode::CANCEL_REQUEST_RECEIVED, parsed.conditionCode);
    EXPECT_EQ(DeliveryCode::DATA_INCOMPLETE, parsed.deliveryCode);
    EXPECT_EQ(FileStatus::DISCARDED_FILESTORE_REJECTION, parsed.fileStatus);
}

TEST_F(FinishedPduTest, DeserializeTooSmallBuffer) {
    FinishedPdu parsed;
    U32 parsedSize = parsed.deserialize(nullptr, 0);
    EXPECT_EQ(static_cast<U32>(0), parsedSize);
}

// -----------------------------------------------------------------------
// Utility function tests
// -----------------------------------------------------------------------

TEST(SerializeDirectivePdu, BasicSerialization) {
    PduHeader header;
    header.version = CFDP_VERSION;
    header.pduType = PduType::FILE_DIRECTIVE;
    header.direction = Direction::TOWARD_RECEIVER;
    header.mode = TransmissionMode::UNACKNOWLEDGED;
    header.crcFlag = false;
    header.largeFileFlag = false;
    header.dataFieldLength = 2;  // 1 byte directive + 1 byte params
    header.segmentationControl = false;
    header.entityIdLength = 1;
    header.segmentMetadataFlag = false;
    header.seqNumLength = 1;
    header.sourceEntityId = 1;
    header.transactionSeqNum = 1;
    header.destinationEntityId = 2;

    U8 params[] = {0x42};
    U8 buf[64];
    U32 totalLen = serializeDirectivePdu(
        header, DirectiveCode::METADATA_PDU,
        params, 1, buf, sizeof(buf)
    );

    EXPECT_EQ(HEADER_SIZE + 2, totalLen);  // header + directive code + 1 byte params
    // Directive code should be at offset HEADER_SIZE
    EXPECT_EQ(static_cast<U8>(DirectiveCode::METADATA_PDU), buf[HEADER_SIZE]);
    EXPECT_EQ(0x42, buf[HEADER_SIZE + 1]);
}

TEST(SerializeDirectivePdu, BufferTooSmall) {
    PduHeader header;
    header.version = CFDP_VERSION;
    header.pduType = PduType::FILE_DIRECTIVE;
    header.direction = Direction::TOWARD_RECEIVER;
    header.mode = TransmissionMode::UNACKNOWLEDGED;
    header.crcFlag = false;
    header.largeFileFlag = false;
    header.dataFieldLength = 2;
    header.segmentationControl = false;
    header.entityIdLength = 1;
    header.segmentMetadataFlag = false;
    header.seqNumLength = 1;
    header.sourceEntityId = 1;
    header.transactionSeqNum = 1;
    header.destinationEntityId = 2;

    U8 params[] = {0x42};
    U8 buf[4];  // Too small
    U32 totalLen = serializeDirectivePdu(
        header, DirectiveCode::METADATA_PDU,
        params, 1, buf, sizeof(buf)
    );
    EXPECT_EQ(static_cast<U32>(0), totalLen);
}

}  // namespace Cfdp
}  // namespace Svc

int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
